###
services:
  frontend:
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.frontend-router.rule=Host(`docsgpt.localhost`) && PathPrefix(`/`)
      - traefik.http.routers.frontend-router.priority=1
      - traefik.http.routers.frontend-router.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=5173
      - custom.traefik.group=openaide

  backend:
    volumes:
      - application-indexes:/app/application/indexes
      - application-inputs:/app/application/inputs
      - application-vectors:/app/application/vectors
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.backend-router.rule=Host(`docsgpt.localhost`) && PathPrefix(`/api/`)
      - traefik.http.routers.backend-router.priority=0
      - traefik.http.routers.backend-router.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=7091
      - custom.traefik.group=openaide
  
  worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - openland

  # TODO postgres? 
  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo:6
    # ports:
    #   - 27017:27017
    networks:
      - openland
    volumes:
      - mongodb-data:/data/db
    restart: always
    # labels:
    #   - traefik.enable=true
    #   - traefik.docker.network=openland
    #   # - traefik.http.routers.mongo.rule=Host(`mongo.localhost`)
    #   # - traefik.http.routers.mongo.entryPoints=web
    #   # - traefik.http.services.mongo.loadbalancer.server.port=27017
    #   - custom.traefik.group=openaide

##
networks:
  openland:
    external: true

volumes:
  mongodb-data:
  application-indexes:
  application-inputs:
  application-vectors:

###