###
name: awesome

# https://aider.chat/docs/install/docker.html
services:
  aider-base:
    profiles:
      - base
    build:
      context: ./local/aider
      dockerfile: docker/Dockerfile
      target: base
    image: openaide/aider-base
    pull_policy: never

  aider:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - AIDER_BASE_IMAGE=openaide/aider-base
    image: openaide/aider
###
