###
###
tcp:
  routers:
    postgres-router:
      entryPoints:
        - postgres
      rule: "HostSNI(`*`)"
      service: postgres-service
      tls: {}

  services:
    postgres-service:
      loadBalancer:
        servers:
          - address: "localhost:5432"

custom:
  traefik:
    group: openaide
