#
name: awesome

services:
  gw:
    privileged: true
    image: openaide/gateway
    ports:
      - "${WEB_PORT:-80}:80"
      - "${ADMIN_PORT:-8080}:8080"
      - "${LLM_PORT:-4000}:4000"
      - "${POSTGRES_PORT:-25432}:25432"
    restart: always
    environment:
      #
      - DATABASE_URL=postgresql://admin:password@localhost:5432/litellm
      - STORE_MODEL_IN_DB=True
      #
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY:-sk-1234}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-1234}
      #
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - db-data:/var/lib/postgresql/data
    networks:
      - openland
    pull_policy: never

networks:
  openland:
    external: true

volumes:
  db-data:
