###
services:
  smolagents:
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    ports:
      - "65432:65432"
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.smolagents-router.rule=Host(`smolagents.localhost`)
      - traefik.http.routers.smolagents-router.entrypoints=web
      - traefik.http.services.smolagents.loadbalancer.server.port=65432
      - custom.traefik.group=openaide

##
networks:
  openland:
    external: true

###