#
name: awesome

services:
  stargate:
    privileged: true
    container_name: "stargate"
    image: openaide/stargate
    ports:
      - "${AI_MCP_PORT:-58080}:58080"
    command: /stargate serve --port 58080 --config /config/mcp.jsonc
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/:/config/
    environment:
      - AI_BASE_URL=${AI_BASE_URL:-http://host.docker.internal:4000}
      - AI_API_KEY=${AI_API_KEY:-sk-1234}
      # 
      - AI_GH_TOKEN=${AI_GH_TOKEN}
    networks:
      - openland
    pull_policy: never

networks:
  openland:
    external: true