#
name: awesome

services:
  stargate:
    privileged: true
    container_name: "stargate"
    image: openaide/stargate
    ports:
      - "${MCP_PORT:-58080}:58080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/:/config/
    environment:
      - AI_BASE_URL=${AI_BASE_URL:-http://host.docker.internal:4000}
      - AI_API_KEY=${AI_API_KEY:-sk-1234}
      - MCP_ROOT=${MCP_ROOT:-/}
    networks:
      - openland
    pull_policy: never

networks:
  openland:
    external: true