#
name: awesome

services:
  stargate:
    privileged: true
    image: openaide/stargate
    ports:
      - "${MCP_PORT:-58080}:58080"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - openland
    pull_policy: never

networks:
  openland:
    external: true