###

services:
  gptr-server:
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:4000/v1
      - OPENAI_API_KEY=sk-1234
      - TAVILY_API_KEY="${TAVILY_API_KEY:-}"
      # - LANGCHAIN_API_KEY="${LANGCHAIN_API_KEY:-}"
      ##
      # local/gpt-researcher/docs/docs/gpt-researcher/gptr/config.md
      # https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/gpt-researcher/gptr/config.md
      # - RETRIEVER=google
      # - GOOGLE_API_KEY=""
      # - RETRIEVER=custom
      - RETRIEVER=searx
      - RETRIEVER_ENDPOINT=http://searxng:8080/
      # - RETRIEVER_ARG_API_KEY=
      #
      - EMBEDDING=openai:text-embedding-3-small
      - FAST_LLM=openai:gpt-4o-mini
      - SMART_LLM=openai:gpt-4o
      - STRATEGIC_LLM=openai:openai:o1-preview
      # - EMBEDDING=ollama:nomic-embed-text
      # - OLLAMA_BASE_URL=http://ollama:11434
      # - FAST_LLM=ollama:llama3
      # - SMART_LLM=ollama:llama3
      # - STRATEGIC_LLM=ollama:llama3
      #
      - CURATE_SOURCES=True
      # - REPORT_FORMAT=IEEE
      - REPORT_FORMAT=Infographic
      - DOC_PATH=/docs
      # - SCRAPER=bs
      - SCRAPER=browser
      #
      - SEARX_URL=
      #
    volumes:
      - gptr-data:/docs
      - ./outputs/:/usr/src/app/outputs/
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.gptr-server-router.rule=Host(`gptr-server.localhost`)
      - traefik.http.routers.gptr-server-router.entrypoints=web
      - traefik.http.services.gptr-server.loadbalancer.server.port=8000
      - custom.traefik.group=openaide

  gptr-nextjs:
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - openland
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.gptr-router.rule=Host(`gptr.localhost`) || Host(`gptr-nextjs.localhost`)
      - traefik.http.routers.gptr-router.entrypoints=web
      - traefik.http.services.gptr.loadbalancer.server.port=3000
      - traefik.http.services.gptr.loadbalancer.server.scheme=http
      - custom.traefik.group=openaide

  searxng:
    image: searxng/searxng
    # ports:
    #   - "${PORT}:8080"
    volumes:
      - "./searxng:/etc/searxng"
    labels:
      - traefik.enable=true
      - traefik.docker.network=openland
      - traefik.http.routers.searxng-router.rule=Host(`searxng.localhost`)
      - traefik.http.routers.searxng-router.entrypoints=web
      - traefik.http.services.searxng.loadbalancer.server.port=8080
      - traefik.http.services.searxng.loadbalancer.server.scheme=http
      - custom.traefik.group=openaide

##
volumes:
  gptr-data:

##
networks:
  openland:
    external: true

###