###
name: awesome

services:
  gptr-server:
    pull_policy: build
    image: openaide/gptr-server
    build: 
      context: ./local/gpt-researcher
      dockerfile: Dockerfile

  gptr-nextjs:
    pull_policy: build
    image: openaide/gptr-nextjs
    # stdin_open: true
    build:
      context: ./local/gpt-researcher/frontend/nextjs
      dockerfile: Dockerfile.dev
      # dockerfile: Dockerfile
 