###
name: awesome

services:
  searxng:
    image: searxng/searxng
    ports:
      - "${SEARXNG_PORT:-48080}:8080"
    environment:
      - SEARXNG_PORT=8080
      - SEARXNG_BIND_ADDRESS=0.0.0.0
    volumes:
      - "./searxng:/etc/searxng"

###