# syntax=docker/dockerfile:1

###
FROM python:3.12-slim

RUN apt-get update && apt-get install -y git

WORKDIR /app

ARG VERSION=v3.1.9

RUN git clone --branch ${VERSION} --depth 1 https://github.com/assafelovic/gpt-researcher.git /app

RUN <<EOF
pip install --upgrade --no-cache-dir pip
pip install --no-cache-dir -r requirements.txt
pip install --no-cache-dir duckduckgo-search
EOF

ENTRYPOINT ["python", "cli.py"]