###
name: awesome

services:
  ollama:
    build:
      context: ./local/ollama
      dockerfile: Dockerfile
      target: runtime-${ARCH:-}
      # target: runtime-arm64
      # target: runtime-amd64
      # target; runtime-rocm
    container_name: ollama
    image: openaide/ollama
    entrypoint: /bin/ollama
    command: serve
###
    